# Generated by Django 4.0 on 2021-12-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
